### ISSUE TITLE
hooksecurefunc(): SelectGossipOption is not a function

### ISSUE THREAD

**Issue by sydbarrett74** [sydbarrett74/HandyNotes_Syd-sWitheredChests#1]
Reported by Ookami313@CurseForge:

I'm unsure if this addon is still being supported ot not, but after the update to 9.0.1 I'm getting the following error upon logging in to the game. Thanks,

```
1x ...rfaceHandyNotes_Syd'sWitheredChests\main.lua:269: hooksecurefunc(): SelectGossipOption is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "@HandyNotes_Syd'sWitheredChests\main.lua"]:269: in main chunk

Locals:
```

**Comment by sydbarrett74** [comment]
Tentatively fixed with commit b5de0e8f. Asking reporter to verify fix.

**Comment by Ookami313** [comment]
Downloaded the update as requested and installed. Re-enabled and I'm still getting the error when logging in or reloading the UI. Thanks.
